const DELETE_MESSAGE = "DATA DELETED SUCCESSFULL";
const UPDATE_MESSAGE = "DATA UPDATED SUCCESSFULL";
const INTERNAL_SERVER_ERR_MESSAGE = "INTERNAL SERVER ERROR";
const ADD_DATA_MESSAGE = "DATA ADDED SUCCESSFULL";
const GET_DATA_MESSAGE = "GET DATA SUCCESSFULL";
const DATA_NOT_FOUND = "DATA NOT FOUND";


export {
  ADD_DATA_MESSAGE,
  DELETE_MESSAGE,
  UPDATE_MESSAGE,
  INTERNAL_SERVER_ERR_MESSAGE,
  GET_DATA_MESSAGE,
  DATA_NOT_FOUND
};
