const DELETE_MESSAGE = "DATA DELETED SUCCESSFULL";
const UPDATE_MESSAGE = "DATA UPDATED SUCCESSFULL";
const INTERNAL_SERVER_ERR_MESSAGE = "INTERNAL SERVER ERROR";
const ADD_DATA_MESSAGE = "DATA ADDED SUCCESSFULL";
const GET_DATA_MESSAGE = "GET DATA SUCCESSFULL";
const ADD_FILE_MESSAGE = "FILE ADDED SUCCESSFULL";

export {
  ADD_DATA_MESSAGE,
  DELETE_MESSAGE,
  UPDATE_MESSAGE,
  INTERNAL_SERVER_ERR_MESSAGE,
  GET_DATA_MESSAGE,
  ADD_FILE_MESSAGE
};
